SHOW DATABASES;

CREATE DATABASE dbelectrodomesticos;

USE dbelectrodomesticos;

CREATE TABLE CLIENTE (
    CODCLI CHAR(6),
    NOMCLI VARCHAR(60),
    APECLI VARCHAR(80),
    EMACLI VARCHAR(80),
    CELCLI CHAR(9),
    DIRCLI VARCHAR(70),
    ESTCLI CHAR(1),
    PRIMARY KEY (CODCLI)
);


CREATE TABLE VENDEDOR (
    CODVEND CHAR(4),
    NOMVEND VARCHAR(60),
    APEVEND VARCHAR(80),
    EMAVEND VARCHAR(80),
    CELVEND CHAR(9),
    DIRVEND VARCHAR(70),
    ESTVEND CHAR(1),
    PRIMARY KEY (CODVEND)
);


CREATE TABLE PRODUCTO (
    CODPRO CHAR(5),
    DESCPRO VARCHAR(80),
    CATPRO CHAR(1),
    PREPRO DECIMAL(8,2),
    STOCKPRO INT,
    ESTPRO CHAR(1),
    PRIMARY KEY (CODPRO)
);


CREATE TABLE PROVEEDOR (
    CODPROV CHAR(5),
    RAZSOCPROV VARCHAR(90),
    RUCPROV VARCHAR(11),
    EMAPROV VARCHAR(70),
    ESTPROV CHAR(1),
    PRIMARY KEY (CODPROV)
);


CREATE TABLE VENTA (
    CODVEN CHAR(5),
    FECVEN DATETIME,
    CODCLI CHAR(4),
    CODVEND CHAR(4),
    ESTVEN CHAR(1),
    PRIMARY KEY (CODVEN)
);


CREATE TABLE VENTADETALLE (
    IDVENDET INT,
    CODVEN CHAR(5),
    CODPRO CHAR(5),
    CANTPRO INT,
    PRIMARY KEY (IDVENDET)
);


CREATE TABLE COMPRA(
    CODCOM CHAR(5),
    FECCOM DATETIME,
    CODVEND CHAR(4),
    CODPROV CHAR(5),
    ESTCOM CHAR(1),
    PRIMARY KEY (CODCOM)
);


CREATE TABLE COMPRADETALLE (
    IDCOMDET INT,
    CODCOM CHAR(5),
    CODPRO CHAR(5),
    CANTPRO INT,
    PRIMARY KEY (IDCOMDET)
);

-- Relaciones
ALTER TABLE VENTA
ADD CONSTRAINT CODCLI_FK
FOREIGN KEY (CODCLI) REFERENCES CLIENTE (CODCLI);

ALTER TABLE VENTA
ADD CONSTRAINT CODVEND_FK
FOREIGN KEY (CODVEND) REFERENCES VENDEDOR (CODVEND);

ALTER TABLE VENTADETALLE
ADD CONSTRAINT CODVEN_FK
FOREIGN KEY (CODVEN) REFERENCES VENTA (CODVEN);

ALTER TABLE VENTADETALLE
ADD CONSTRAINT CODPRO_FK
FOREIGN KEY (CODPRO) REFERENCES PRODUCTO (CODPRO);

ALTER TABLE COMPRADETALLE
ADD CONSTRAINT CODPROD_FK
FOREIGN KEY (CODPRO) REFERENCES PRODUCTO (CODPRO);

ALTER TABLE COMPRADETALLE
ADD CONSTRAINT CODCOM_FK
FOREIGN KEY (CODCOM) REFERENCES COMPRA (CODCOM);

ALTER TABLE COMPRA
ADD CONSTRAINT CODPROV_FK
FOREIGN KEY (CODPROV) REFERENCES PROVEEDOR (CODPROV);

ALTER TABLE COMPRA
ADD CONSTRAINT CODVENDE_FK
FOREIGN KEY (CODVEND) REFERENCES VENDEDOR (CODVEND);